// @ts-ignore
import React from "react";
import ReactDOM from "react-dom/client";
import { HelmetProvider } from "react-helmet-async";
import "./styles/index.css";
import "./i18n";
import { InstallBanner } from "./components/InstallBanner";
import { IOSInstallHint } from "./components/IOSInstallHint";

import { RouterProvider } from "react-router-dom";
import { router } from "./app/router";

// Register the PWA Service Worker generated by Vite
import { registerSW } from "virtual:pwa-register";

registerSW({ immediate: true });

ReactDOM.createRoot(document.getElementById("root")!).render(
    <React.StrictMode>
        <HelmetProvider>
            <RouterProvider router={router} />
            <InstallBanner />
            <IOSInstallHint />
        </HelmetProvider>
    </React.StrictMode>
);